export { default as Homescreen } from './Homescreen/Homescreen'
export { default as RecipeScreen } from './Recipescreen/Recipescreen'
export { default as SurpriseMeScreen } from './SurpriseMeScreen/SurpriseMeScreen'
export { default as StartScreen } from './StartScreen/StartScreen'
export { default as MyFridgeScreen } from './MyFridgeScreen/MyFridgeScreen'
export { default as SettingScreen } from './SettingsScreen/SettingsScreen'
export { default as FavoritesScreen } from './FavoritesScreen/FavoritesScreen'